name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-
          restore-keys: |
            ${{ runner.os }}-node-
      
      - run: mkdir -p public
      - run: touch public/.nojekyll
      - run: cp -fr images public/images
      - run: npx -y @marp-team/marp-cli@latest jica-seminar-2024.md -o public/index.html
      - run: npx -y @marp-team/marp-cli@latest jica-seminar-2024.md -o public/jica-seminar-2024.pptx --allow-local-files
      - run: npx -y @marp-team/marp-cli@latest jica-seminar-2024.md -o public/jica-seminar-2024.pdf --allow-local-files

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public